[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Asynchronous, GTK+-based, GUI library, inspired by Elm, written in Rust"
documentation = "https://docs.rs/relm/"
license = "MIT"
name = "relm"
readme = "README.adoc"
repository = "https://github.com/antoyo/relm"
version = "0.16.0"

[badges.appveyor]
branch = "master"
repository = "antoyo/relm"

[badges.travis-ci]
branch = "master"
repository = "antoyo/relm"

[dependencies]
cairo-rs = "^0.6.0" # TODO: make these dependencies optional (to have something like relm-state)?
glib = "^0.7.0"
gobject-sys = "^0.8.0"
gtk = "^0.6.0"
log = "^0.4.6"
quote = "0.6"
slab = "^0.4.2"

[dependencies.syn]
features = ["full"]
version = "0.15"

[dev-dependencies]
chrono = "0.4"
gdk = "^0.10.0"
rand = "^0.5.1"
gtk-test = "^0.3"

[dev-dependencies.gio]
version = "^0.6.0"

[dev-dependencies.relm-derive]
path = "relm-derive"
version = "^0.16.0"

[dev-dependencies.relm-test]
path = "relm-test"
version = "^0.16.0"

[features]
default = ["unstable"]
hidpi = ["cairo-rs/v1_14"]
nightly = []
unstable = []

[[package.metadata.release.pre-release-replacements]]
file = "README.adoc"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""
